import { collections, type CollectionName, type SigmoraUser, type WorkspaceMember } from '@/lib/domain';
import type {
  AnalysisJob,
  AnalysisResult,
  ApprovalRecord,
  Asset,
  AssetFolder,
  BenchmarkCollection,
  BlogDraft,
  Campaign,
  CmsConnection,
  CompetitorAccount,
  ConnectedAccount,
  PaymentAttempt,
  PaymentCustomer,
  Playbook,
  PromptRun,
  PromptTemplate,
  ActivationEvent,
  PublishingQueueItem,
  RemixJob,
  RemixOutput,
  SubscriptionRecord,
  TrendSnapshot,
  WatchlistAccount,
  Workspace,
} from '@/lib/domain';

const now = '2026-03-10T09:00:00.000Z';
const demoMembers: WorkspaceMember[] = [
  { userId: 'user_1', role: 'owner' },
  { userId: 'user_2', role: 'editor' },
  { userId: 'user_3', role: 'viewer' },
];

export const demoUsers: SigmoraUser[] = [
  {
    id: 'user_1',
    createdAt: now,
    updatedAt: now,
    email: 'owner@sigmora.ai',
    displayName: 'Workspace Owner',
    defaultWorkspaceId: 'ws_sigmora_lab',
  },
  {
    id: 'user_2',
    createdAt: now,
    updatedAt: now,
    email: 'editor@sigmora.ai',
    displayName: 'Creative Editor',
    defaultWorkspaceId: 'ws_sigmora_lab',
  },
  {
    id: 'user_3',
    createdAt: now,
    updatedAt: now,
    email: 'viewer@sigmora.ai',
    displayName: 'Analyst Reviewer',
    defaultWorkspaceId: 'ws_sigmora_lab',
  },
];

export const demoWorkspace: Workspace = {
  id: 'ws_sigmora_lab',
  createdAt: now,
  updatedAt: now,
  name: 'Sigmora Lab',
  slug: 'sigmora-lab',
  plan: 'team',
  members: demoMembers,
  billingProvider: 'stripe',
  billingCustomerId: 'cus_sigmora_lab',
  billingState: 'trialing',
};

export const demoAssets: Asset[] = [
  {
    id: 'asset_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    title: 'Creator Hook Breakdown',
    platform: 'tiktok',
    source: 'import',
    status: 'ready',
    durationSeconds: 34,
    tags: ['hook', 'demo', 'cta'],
    transcriptReady: true,
    benchmarkEligible: true,
    storageProvider: 'content-engine',
    contentEngineContentId: 'cnt_asset_1',
    contentAccessMode: 'public',
    contentSyncStatus: 'active',
    sourceUrl: 'https://tiktok.com/@creator/video/example1',
    transcript: [
      { text: 'Stop scrolling if you want more sales.', startSecond: 0, endSecond: 3 },
      { text: 'Most brands are making this one mistake with their ads.', startSecond: 3, endSecond: 7 },
      { text: 'They focus on features instead of the transformation.', startSecond: 7, endSecond: 11 },
      { text: 'Here is what actually works. Watch this demo.', startSecond: 11, endSecond: 15 },
      { text: 'See how the before and after creates instant trust.', startSecond: 15, endSecond: 21 },
      { text: 'This simple shift doubled conversion rates for three brands last month.', startSecond: 21, endSecond: 27 },
      { text: 'Link in bio to get the full playbook. Follow for more.', startSecond: 27, endSecond: 34 },
    ],
    notes: 'Strong opener with pattern interrupt. Proof section lands early. CTA could be tighter.',
  },
  {
    id: 'asset_2',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    title: 'Problem-Solution Ad Variant',
    platform: 'instagram',
    source: 'upload',
    status: 'processing',
    durationSeconds: 27,
    tags: ['problem', 'testimonial'],
    transcriptReady: false,
    benchmarkEligible: false,
    storageProvider: 'content-engine',
    contentEngineContentId: null,
    contentAccessMode: 'private',
    contentSyncStatus: 'pending',
  },
  {
    id: 'asset_3',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    title: 'Trend Stitch Reference',
    platform: 'youtube',
    source: 'saved-benchmark',
    status: 'ready',
    durationSeconds: 42,
    tags: ['trend', 'hook'],
    transcriptReady: true,
    benchmarkEligible: true,
    storageProvider: 'content-engine',
    contentEngineContentId: 'cnt_asset_3',
    contentAccessMode: 'public',
    contentSyncStatus: 'active',
    sourceUrl: 'https://youtube.com/shorts/example3',
    transcript: [
      { text: 'This trend is about to blow up and nobody is talking about it.', startSecond: 0, endSecond: 4 },
      { text: 'I analyzed 200 viral shorts from the last week.', startSecond: 4, endSecond: 8 },
      { text: 'The pattern is clear. Fast cuts, text overlays, and a specific pacing structure.', startSecond: 8, endSecond: 14 },
      { text: 'Let me break down exactly what they all have in common.', startSecond: 14, endSecond: 18 },
      { text: 'Scene one: pattern interrupt with motion. Scene two: problem in under three seconds.', startSecond: 18, endSecond: 25 },
      { text: 'Scene three: proof with visuals, not words. Scene four: CTA with urgency.', startSecond: 25, endSecond: 32 },
      { text: 'If you use this framework you will see results this week. Save this video.', startSecond: 32, endSecond: 42 },
    ],
    notes: 'Excellent educational format. Strong analytical hook. Good for benchmark reference.',
  },
];

export const demoBenchmarkCollections: BenchmarkCollection[] = [
  {
    id: 'bench_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    title: 'High-Tension Hooks',
    description: 'References with strong open loops in the first three seconds.',
    assetIds: ['asset_1', 'asset_3'],
    focus: 'hooks',
  },
  {
    id: 'bench_2',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    title: 'Fast Proof Sequences',
    description: 'Examples where demonstration moments land before second 12.',
    assetIds: ['asset_1'],
    focus: 'proof',
  },
];

export const demoPromptTemplates: PromptTemplate[] = [
  {
    id: 'prompt_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    title: 'Benchmark-to-Scene Plan',
    objective: 'Turn benchmark patterns into a scene-by-scene output.',
    body: 'Given the following benchmark analysis:\n\n{{benchmark_analysis}}\n\nGenerate a scene-by-scene plan for a {{duration}}-second {{platform}} video that:\n1. Opens with a hook matching the benchmark tension level\n2. Introduces the problem within {{hook_window}} seconds\n3. Delivers proof/demo in the middle third\n4. Closes with a CTA that references {{offer}}\n\nTarget audience: {{audience}}\nTone: {{tone}}',
    version: 3,
    lastOutcome: 'strong',
    tags: ['scene-plan', 'benchmark', 'generation'],
  },
  {
    id: 'prompt_2',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    title: 'Offer-Angle Variant',
    objective: 'Generate three hook variants around a single product promise.',
    body: 'Product: {{product}}\nCore promise: {{promise}}\nPlatform: {{platform}}\n\nGenerate 3 distinct hook variants (each under 3 seconds when spoken):\n\nVariant A - Pattern interrupt: Use a surprising statement or contrarian take\nVariant B - Question hook: Open with a specific, relatable question\nVariant C - Social proof: Lead with a result or testimonial\n\nFor each variant, also suggest:\n- Follow-up line (seconds 3-6)\n- Visual direction\n- Text overlay copy',
    version: 2,
    lastOutcome: 'mixed',
    tags: ['hooks', 'variants', 'offers'],
  },
];

export const demoPromptRuns: PromptRun[] = [
  {
    id: 'run_1',
    createdAt: '2026-03-09T14:00:00.000Z',
    updatedAt: '2026-03-09T14:00:00.000Z',
    workspaceId: demoWorkspace.id,
    promptId: 'prompt_1',
    promptVersion: 3,
    input: 'Benchmark: High-Tension Hooks collection. Duration: 30s. Platform: TikTok. Offer: AI editing tool. Audience: content creators.',
    output: 'Scene 1 (0-3s): Pattern interrupt — creator stares at camera, text overlay "Your ads are boring." Quick zoom.\nScene 2 (3-8s): Problem — "I tested 50 ads last month. 90% had the same mistake."\nScene 3 (8-18s): Proof — Screen recording showing before/after edit with tool. Split screen comparison.\nScene 4 (18-24s): Demo — "Watch what happens when you apply this one framework."\nScene 5 (24-30s): CTA — "Link in bio. Free trial. Your competitors are already using this."',
    outcome: 'strong',
    benchmarkCollectionId: 'bench_1',
  },
  {
    id: 'run_2',
    createdAt: '2026-03-08T10:00:00.000Z',
    updatedAt: '2026-03-08T10:00:00.000Z',
    workspaceId: demoWorkspace.id,
    promptId: 'prompt_1',
    promptVersion: 2,
    input: 'Benchmark: Fast Proof Sequences. Duration: 25s. Platform: Instagram. Offer: Skincare brand.',
    output: 'Scene 1 (0-2s): Hook — Close-up of skin transformation, no words, just visual.\nScene 2 (2-6s): Problem — "Everyone told me nothing would work."\nScene 3 (6-16s): Proof — Time-lapse of 30-day results with date stamps.\nScene 4 (16-25s): CTA — "Same routine. Link in bio."',
    outcome: 'mixed',
    benchmarkCollectionId: 'bench_2',
  },
  {
    id: 'run_3',
    createdAt: '2026-03-07T16:00:00.000Z',
    updatedAt: '2026-03-07T16:00:00.000Z',
    workspaceId: demoWorkspace.id,
    promptId: 'prompt_2',
    promptVersion: 2,
    input: 'Product: Sigmora. Promise: Make viral videos systematically. Platform: TikTok.',
    output: 'Variant A — "Stop guessing what makes videos go viral."\nFollow-up: "I reverse-engineered 500 viral TikToks. Here is the pattern."\nVisual: Creator at desk with analytics dashboard behind.\nText overlay: "The viral formula nobody shares"\n\nVariant B — "Why do some creators hit 1M views every week?"\nFollow-up: "It is not luck. It is structure. Let me show you."\nVisual: Phone screen showing view counts stacking up.\nText overlay: "1M views. Every. Single. Week."\n\nVariant C — "This tool helped 200 creators double their views in 30 days."\nFollow-up: "No trends to chase. No algorithm hacks. Just data."\nVisual: Testimonial screenshots scrolling.\nText overlay: "200+ creators. 2x views."',
    outcome: 'strong',
  },
];

export const demoAnalysisJobs: AnalysisJob[] = [
  {
    id: 'analysis_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    assetId: 'asset_1',
    status: 'completed',
    jobType: 'benchmark-analysis',
    outputSummary: 'Hook pacing extracted, proof moment marked at 00:11, CTA density moderate.',
  },
  {
    id: 'analysis_2',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    assetId: 'asset_2',
    status: 'running',
    jobType: 'library-analysis',
    outputSummary: 'Transcript and scene segmentation in progress.',
  },
];

export const demoAnalysisResults: AnalysisResult[] = [
  {
    id: 'result_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    assetId: 'asset_1',
    hookScore: 82,
    pacingScore: 76,
    proofScore: 79,
    ctaScore: 61,
    retentionRisk: 'medium',
    recommendedHookWindowSeconds: 3,
    recommendedCtaWindowSeconds: 24,
    scenes: [
      { label: 'Pattern interrupt opener', startSecond: 0, endSecond: 3, purpose: 'hook' },
      { label: 'Problem framing', startSecond: 3, endSecond: 10, purpose: 'problem' },
      { label: 'Product proof', startSecond: 10, endSecond: 21, purpose: 'proof' },
      { label: 'Close and CTA', startSecond: 21, endSecond: 34, purpose: 'cta' },
    ],
    recommendations: [
      { title: 'Tighten the first sentence', rationale: 'The hook window is acceptable but can hit faster in the first two seconds.' },
      { title: 'Move proof earlier', rationale: 'Proof starts after second 10, which is late for short-form paid creative.' },
      { title: 'Strengthen the CTA close', rationale: 'The current CTA density looks weaker than the hook and proof sections.' },
    ],
    summary: 'Strong opener and good proof density, but the CTA lands too softly relative to the first half.',
  },
  {
    id: 'result_3',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    assetId: 'asset_3',
    hookScore: 88,
    pacingScore: 82,
    proofScore: 74,
    ctaScore: 70,
    retentionRisk: 'low',
    recommendedHookWindowSeconds: 4,
    recommendedCtaWindowSeconds: 32,
    scenes: [
      { label: 'Curiosity hook', startSecond: 0, endSecond: 4, purpose: 'hook' },
      { label: 'Authority framing', startSecond: 4, endSecond: 14, purpose: 'problem' },
      { label: 'Framework breakdown', startSecond: 14, endSecond: 32, purpose: 'proof' },
      { label: 'CTA with urgency', startSecond: 32, endSecond: 42, purpose: 'cta' },
    ],
    recommendations: [
      { title: 'Maintain the curiosity gap', rationale: 'The opener creates strong anticipation. Preserve the specific claim structure.' },
      { title: 'Compress the framework section', rationale: 'The proof section is long at 18 seconds. Consider cutting to 12-14 seconds for better pacing.' },
      { title: 'Add visual proof', rationale: 'The proof relies on verbal explanation. Adding screen recordings or data visuals would strengthen retention.' },
    ],
    summary: 'Excellent hook with strong educational framing. Proof section is informative but could be tighter. CTA has good urgency.',
  },
];

export const demoRemixJobs: RemixJob[] = [
  {
    id: 'remix_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    benchmarkCollectionId: 'bench_1',
    promptId: 'prompt_1',
    status: 'ready',
    targetOffer: 'AI product demo for ecommerce brands',
    outputType: 'scene-plan',
  },
  {
    id: 'remix_2',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    benchmarkCollectionId: 'bench_2',
    status: 'draft',
    targetOffer: 'Short-form ad concept for a workflow tool',
    outputType: 'script',
  },
];

export const demoRemixOutputs: RemixOutput[] = [
  {
    id: 'remix_out_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    remixJobId: 'remix_1',
    outputType: 'scene-plan',
    title: 'Ecommerce AI Demo — Scene Plan v1',
    content: 'A 30-second TikTok scene plan targeting ecommerce brand owners who want to automate product demos.',
    scenes: [
      {
        sceneNumber: 1,
        duration: '0-3s',
        visual: 'Close-up of hand swiping through a cluttered product page. Quick zoom to face.',
        audio: 'No music. Just the swipe sound.',
        text: '"Your product pages are losing you sales."',
        purpose: 'Pattern interrupt hook',
      },
      {
        sceneNumber: 2,
        duration: '3-8s',
        visual: 'Split screen: messy product listing vs. clean AI-generated demo.',
        audio: 'Light tension music begins.',
        text: '"I tested this AI tool on 12 stores last week."',
        purpose: 'Problem + authority',
      },
      {
        sceneNumber: 3,
        duration: '8-20s',
        visual: 'Screen recording of tool in action. Before/after product demos side by side.',
        audio: 'Music builds. Quick cuts every 2-3 seconds.',
        text: '"Every store saw at least 40% more time on page."',
        purpose: 'Proof with data',
      },
      {
        sceneNumber: 4,
        duration: '20-30s',
        visual: 'Creator back on camera. Phone showing results dashboard.',
        audio: 'Music resolves.',
        text: '"Link in bio. Free trial. Your competitors already started."',
        purpose: 'CTA with urgency',
      },
    ],
  },
];

export const demoTrendSnapshots: TrendSnapshot[] = [
  {
    id: 'trend_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    title: 'Whisper-to-Shout Hook',
    category: 'hook-format',
    platform: 'tiktok',
    description: 'Creators start speaking in a quiet whisper then suddenly raise their voice for emphasis. Creates a jarring attention grab in the first 2 seconds.',
    exampleCount: 847,
    velocity: 'rising',
    saturation: 'low',
    recommendedAction: 'Adopt immediately. Low saturation means early movers get disproportionate reach. Works best with product reveals.',
    detectedAt: '2026-03-08T00:00:00.000Z',
  },
  {
    id: 'trend_2',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    title: 'Data Wall Visual',
    category: 'visual-style',
    platform: 'instagram',
    description: 'Screenshots of analytics dashboards, spreadsheets, or data tables used as B-roll proof. Establishes credibility without requiring verbal proof.',
    exampleCount: 1243,
    velocity: 'stable',
    saturation: 'medium',
    recommendedAction: 'Use selectively as supporting visual. Pair with a verbal hook that contextualizes the data. Avoid using as the primary hook.',
    detectedAt: '2026-03-05T00:00:00.000Z',
  },
  {
    id: 'trend_3',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    title: 'Reverse Testimonial',
    category: 'narrative-pattern',
    platform: 'tiktok',
    description: 'Starting with the result first, then revealing the process. "I made $10K this month. Here is how I did it starting from zero." Inverts traditional story arc.',
    exampleCount: 2156,
    velocity: 'stable',
    saturation: 'high',
    recommendedAction: 'Still effective but saturating. Differentiate by adding unique proof elements or unexpected twists in the reveal.',
    detectedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'trend_4',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    title: 'Silent Demo Reel',
    category: 'audio-trend',
    platform: 'youtube',
    description: 'Product demos with no voiceover, only ambient sound and text overlays. Performs well in Shorts where users browse with sound off.',
    exampleCount: 534,
    velocity: 'rising',
    saturation: 'low',
    recommendedAction: 'Strong fit for product-focused content. Create parallel versions: one with voiceover for TikTok, one silent for YouTube Shorts.',
    detectedAt: '2026-03-09T00:00:00.000Z',
  },
  {
    id: 'trend_5',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    title: 'Triple CTA Stack',
    category: 'cta-technique',
    platform: 'tiktok',
    description: 'Ending with three rapid CTAs: follow, save, and link. Delivered in under 4 seconds with text overlay reinforcement.',
    exampleCount: 1890,
    velocity: 'declining',
    saturation: 'high',
    recommendedAction: 'Declining effectiveness due to oversaturation. Consider single specific CTA with unique phrasing instead.',
    detectedAt: '2026-02-20T00:00:00.000Z',
  },
];

export const demoCompetitorAccounts: CompetitorAccount[] = [
  {
    id: 'comp_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    handle: '@ugcmastery',
    platform: 'tiktok',
    displayName: 'UGC Mastery',
    followerCount: 245000,
    avgViews: 89000,
    avgEngagementRate: 4.2,
    topHookStyle: 'Pattern interrupt with text overlay',
    postingFrequency: '2x daily',
    lastScannedAt: '2026-03-09T12:00:00.000Z',
    notes: 'Consistently strong hooks. Uses the whisper-to-shout format early. Proof sections always include screen recordings.',
    watchlistPriority: 'high',
  },
  {
    id: 'comp_2',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    handle: '@creatorlab',
    platform: 'instagram',
    displayName: 'Creator Lab',
    followerCount: 182000,
    avgViews: 45000,
    avgEngagementRate: 3.8,
    topHookStyle: 'Question-based with quick cuts',
    postingFrequency: '1x daily',
    lastScannedAt: '2026-03-08T15:00:00.000Z',
    notes: 'Strong educational content. Good use of data visuals as proof. CTAs are often weak — typically just "follow for more".',
    watchlistPriority: 'medium',
  },
  {
    id: 'comp_3',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    handle: '@adscience',
    platform: 'youtube',
    displayName: 'Ad Science',
    followerCount: 520000,
    avgViews: 125000,
    avgEngagementRate: 5.1,
    topHookStyle: 'Data-driven contrarian opener',
    postingFrequency: '3x weekly',
    lastScannedAt: '2026-03-07T18:00:00.000Z',
    notes: 'Highest engagement rate in the space. Uses longer-form educational content that gets repurposed into Shorts. Study their scene transitions.',
    watchlistPriority: 'high',
  },
];

export const demoPlaybooks: Playbook[] = [
  {
    id: 'playbook_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    title: 'Ecommerce Product Launch',
    description: 'End-to-end playbook for launching a new product with short-form video across TikTok and Instagram. Includes hook templates, proof frameworks, and CTA structures optimized for conversion.',
    niche: 'Ecommerce / DTC',
    benchmarkCollectionIds: ['bench_1', 'bench_2'],
    promptTemplateIds: ['prompt_1', 'prompt_2'],
    brandGuardrails: [
      'No false scarcity or fake countdown timers',
      'All testimonials must be from real customers',
      'Product claims must be substantiated with data',
      'No competitor bashing — focus on own strengths',
    ],
    targetPlatforms: ['tiktok', 'instagram'],
    status: 'active',
  },
  {
    id: 'playbook_2',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    title: 'SaaS Demo Content',
    description: 'Playbook for B2B SaaS companies creating demo-style short-form content. Emphasizes screen recordings, data visuals, and educational hooks.',
    niche: 'B2B SaaS',
    benchmarkCollectionIds: ['bench_1'],
    promptTemplateIds: ['prompt_1'],
    brandGuardrails: [
      'Keep technical jargon minimal',
      'Always show the product in action, not just talk about it',
      'Include specific metrics or results where possible',
    ],
    targetPlatforms: ['youtube', 'linkedin'],
    status: 'active',
  },
];

export const demoConnectedAccounts: ConnectedAccount[] = [
  {
    id: 'conn_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    platform: 'tiktok',
    handle: '@sigmora_official',
    displayName: 'Sigmora Official',
    status: 'connected',
    capabilities: ['publish', 'analytics', 'schedule'],
    lastSyncAt: '2026-03-10T08:00:00.000Z',
  },
  {
    id: 'conn_2',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    platform: 'instagram',
    handle: '@sigmora.ai',
    displayName: 'Sigmora AI',
    status: 'connected',
    capabilities: ['publish', 'analytics'],
    lastSyncAt: '2026-03-09T22:00:00.000Z',
  },
  {
    id: 'conn_3',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    platform: 'youtube',
    handle: '@SigmoraHQ',
    displayName: 'Sigmora HQ',
    status: 'expired',
    capabilities: ['publish'],
    lastSyncAt: '2026-02-28T10:00:00.000Z',
  },
];

export const demoCampaigns: Campaign[] = [
  {
    id: 'campaign_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    title: 'Q1 Product Launch Blitz',
    description: 'Multi-platform campaign for the spring product launch. TikTok and Instagram simultaneously with platform-adapted variants.',
    connectedAccountIds: ['conn_1', 'conn_2'],
    platforms: ['tiktok', 'instagram'],
    automationMode: 'review-first',
    status: 'active',
    scheduledAt: '2026-03-12T09:00:00.000Z',
    remixJobIds: ['remix_1'],
    playbookId: 'playbook_1',
  },
  {
    id: 'campaign_2',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    title: 'Evergreen SaaS Demos',
    description: 'Ongoing YouTube Shorts campaign with educational demo content. Review-first mode.',
    connectedAccountIds: ['conn_3'],
    platforms: ['youtube'],
    automationMode: 'review-first',
    status: 'draft',
    scheduledAt: null,
    remixJobIds: ['remix_2'],
    playbookId: 'playbook_2',
  },
];

export const demoPublishingQueue: PublishingQueueItem[] = [
  {
    id: 'pub_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    campaignId: 'campaign_1',
    connectedAccountId: 'conn_1',
    platform: 'tiktok',
    title: 'Ecommerce AI Demo — TikTok Variant',
    content: 'Stop scrolling if you sell online. Your product pages are losing you money. I tested this AI tool on 12 stores...',
    status: 'scheduled',
    scheduledAt: '2026-03-12T14:00:00.000Z',
    publishedAt: null,
    retryCount: 0,
    errorMessage: null,
  },
  {
    id: 'pub_2',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    campaignId: 'campaign_1',
    connectedAccountId: 'conn_2',
    platform: 'instagram',
    title: 'Ecommerce AI Demo — Instagram Reel',
    content: 'Your product pages are losing you sales. Here is what 12 stores did differently...',
    status: 'review-required',
    scheduledAt: '2026-03-12T15:00:00.000Z',
    publishedAt: null,
    retryCount: 0,
    errorMessage: null,
  },
  {
    id: 'pub_3',
    createdAt: '2026-03-08T09:00:00.000Z',
    updatedAt: '2026-03-08T10:30:00.000Z',
    workspaceId: demoWorkspace.id,
    campaignId: null,
    connectedAccountId: 'conn_1',
    platform: 'tiktok',
    title: 'Quick hook test — pattern interrupt',
    content: 'You are wasting money on ads that nobody watches past second 2...',
    status: 'published',
    scheduledAt: '2026-03-08T10:00:00.000Z',
    publishedAt: '2026-03-08T10:01:00.000Z',
    retryCount: 0,
    errorMessage: null,
  },
];

export const demoWatchlistAccounts: WatchlistAccount[] = [
  {
    id: 'watch_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    handle: '@viralhooks',
    platform: 'tiktok',
    displayName: 'Viral Hooks Daily',
    automationMode: 'review-first',
    researchFrequency: 'daily',
    lastResearchAt: '2026-03-09T06:00:00.000Z',
    nextResearchAt: '2026-03-10T06:00:00.000Z',
    postsScanned: 47,
    patternsExtracted: 12,
    contentsGenerated: 5,
    status: 'active',
  },
  {
    id: 'watch_2',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    handle: '@adsbreakdown',
    platform: 'instagram',
    displayName: 'Ads Breakdown',
    automationMode: 'manual',
    researchFrequency: 'weekly',
    lastResearchAt: '2026-03-03T08:00:00.000Z',
    nextResearchAt: '2026-03-10T08:00:00.000Z',
    postsScanned: 23,
    patternsExtracted: 8,
    contentsGenerated: 0,
    status: 'active',
  },
  {
    id: 'watch_3',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    handle: '@shortformstudio',
    platform: 'youtube',
    displayName: 'Short Form Studio',
    automationMode: 'fire-and-forget',
    researchFrequency: 'weekly',
    lastResearchAt: '2026-03-05T12:00:00.000Z',
    nextResearchAt: '2026-03-12T12:00:00.000Z',
    postsScanned: 15,
    patternsExtracted: 6,
    contentsGenerated: 3,
    status: 'paused',
  },
];

export const demoApprovalRecords: ApprovalRecord[] = [
  {
    id: 'approval_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    entityType: 'remix-output',
    entityId: 'remix_out_1',
    state: 'approved',
    reviewerUserId: 'user_2',
    comment: 'Strong scene plan. Good hook timing. Approved for publishing.',
    decidedAt: '2026-03-09T16:00:00.000Z',
  },
  {
    id: 'approval_2',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    entityType: 'publishing-item',
    entityId: 'pub_2',
    state: 'pending',
    reviewerUserId: null,
    comment: '',
    decidedAt: null,
  },
  {
    id: 'approval_3',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    entityType: 'campaign',
    entityId: 'campaign_2',
    state: 'revision-requested',
    reviewerUserId: 'user_1',
    comment: 'The SaaS demo content needs more specific metrics in the proof section before we launch.',
    decidedAt: '2026-03-09T11:00:00.000Z',
  },
];

export const demoCmsConnections: CmsConnection[] = [
  {
    id: 'cms_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    provider: 'wordpress',
    name: 'Company Blog',
    baseUrl: 'https://blog.sigmora.ai',
    status: 'connected',
    capabilities: ['create-draft', 'publish', 'schedule'],
    lastSyncAt: '2026-03-10T07:00:00.000Z',
  },
  {
    id: 'cms_2',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    provider: 'ghost',
    name: 'Knowledge Base',
    baseUrl: 'https://learn.sigmora.ai',
    status: 'connected',
    capabilities: ['create-draft', 'publish'],
    lastSyncAt: '2026-03-09T20:00:00.000Z',
  },
];

export const demoBlogDrafts: BlogDraft[] = [
  {
    id: 'blog_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    cmsConnectionId: 'cms_1',
    title: 'How to Structure a 30-Second Product Demo Video',
    body: 'Most product demos fail in the first 3 seconds. Here is a framework for structuring short-form product demos that actually convert, based on analysis of 200+ high-performing videos.\n\n## The 4-Scene Framework\n\n### Scene 1: Pattern Interrupt (0-3s)\nOpen with something unexpected. A bold claim, a visual surprise, or a contrarian statement. The goal is not to explain — it is to stop the scroll.\n\n### Scene 2: Problem Framing (3-8s)\nName the specific problem your audience faces. Be concrete. "Your product pages load too slowly" beats "Improve your online presence."\n\n### Scene 3: Proof with Data (8-22s)\nShow, don\'t tell. Screen recordings, before/after comparisons, specific metrics. This is where trust is built.\n\n### Scene 4: CTA with Urgency (22-30s)\nOne specific call to action. Link in bio, free trial, limited offer. Avoid stacking multiple CTAs.',
    sourceType: 'remix',
    sourceId: 'remix_out_1',
    status: 'draft',
    scheduledAt: null,
    publishedAt: null,
    publishedUrl: null,
  },
  {
    id: 'blog_2',
    createdAt: '2026-03-07T09:00:00.000Z',
    updatedAt: '2026-03-07T14:00:00.000Z',
    workspaceId: demoWorkspace.id,
    cmsConnectionId: 'cms_2',
    title: '5 Hook Patterns That Are Working Right Now on TikTok',
    body: 'We analyzed trending TikTok content over the past month and identified 5 hook patterns that consistently drive higher retention...',
    sourceType: 'manual',
    sourceId: null,
    status: 'published',
    scheduledAt: null,
    publishedAt: '2026-03-07T14:00:00.000Z',
    publishedUrl: 'https://learn.sigmora.ai/5-hook-patterns',
  },
];

export const demoAssetFolders: AssetFolder[] = [
  {
    id: 'folder_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    name: 'Hook References',
    parentId: null,
    assetIds: ['asset_1', 'asset_3'],
    color: '#3b9c97',
  },
  {
    id: 'folder_2',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    name: 'Client: Acme Corp',
    parentId: null,
    assetIds: ['asset_2'],
    color: '#c46832',
  },
  {
    id: 'folder_3',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    name: 'Proof Techniques',
    parentId: 'folder_1',
    assetIds: ['asset_1'],
    color: '#7a6bbf',
  },
];

export const demoPaymentCustomers: PaymentCustomer[] = [
  {
    id: 'pc_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    userId: 'user_1',
    email: 'owner@sigmora.ai',
    provider: 'paystack',
    providerCustomerId: 'CUS_demo_paystack',
  },
];

export const demoPaymentAttempts: PaymentAttempt[] = [
  {
    id: 'pay_demo_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    userId: 'user_1',
    provider: 'paystack',
    txRef: 'pay_demo_1',
    amount: 49,
    currency: 'USD',
    status: 'succeeded',
    checkoutUrl: null,
    providerReference: 'PSK_REF_1',
    fallbackUsed: false,
    planKey: 'starter_monthly',
  },
];

export const demoSubscriptions: SubscriptionRecord[] = [
  {
    id: 'sub_1',
    createdAt: now,
    updatedAt: now,
    workspaceId: demoWorkspace.id,
    userId: 'user_1',
    provider: 'paystack',
    providerSubscriptionId: 'SUB_demo_1',
    providerCustomerId: 'CUS_demo_paystack',
    planKey: 'starter_monthly',
    status: 'trialing',
    interval: 'month',
    amount: 49,
    currency: 'USD',
  },
];

export const demoActivationEvents: ActivationEvent[] = [
  {
    id: 'activation_1',
    createdAt: '2026-03-10T07:45:00.000Z',
    updatedAt: '2026-03-10T07:45:00.000Z',
    workspaceId: demoWorkspace.id,
    userId: 'user_1',
    userEmail: 'owner@sigmora.ai',
    userName: 'Workspace Owner',
    eventType: 'remix_created',
    stage: 'activated',
    sourcePath: `/workspaces/${demoWorkspace.slug}/jobs`,
    metadata: {
      jobId: 'remix_1',
    },
  },
  {
    id: 'activation_2',
    createdAt: '2026-03-06T10:00:00.000Z',
    updatedAt: '2026-03-06T10:00:00.000Z',
    workspaceId: demoWorkspace.id,
    userId: 'user_2',
    userEmail: 'editor@sigmora.ai',
    userName: 'Creative Editor',
    eventType: 'analysis_completed',
    stage: 'analysis',
    sourcePath: `/workspaces/${demoWorkspace.slug}/library/asset_1`,
    metadata: {
      assetId: 'asset_1',
    },
  },
  {
    id: 'activation_3',
    createdAt: '2026-03-04T08:30:00.000Z',
    updatedAt: '2026-03-04T08:30:00.000Z',
    workspaceId: demoWorkspace.id,
    userId: 'user_3',
    userEmail: 'viewer@sigmora.ai',
    userName: 'Analyst Reviewer',
    eventType: 'activation_page_viewed',
    stage: 'started',
    sourcePath: `/workspaces/${demoWorkspace.slug}/activate`,
    metadata: {},
  },
];

export const mockDatabase: Record<CollectionName, unknown[]> = {
  [collections.users]: demoUsers,
  [collections.workspaces]: [demoWorkspace],
  [collections.assets]: demoAssets,
  [collections.benchmarkCollections]: demoBenchmarkCollections,
  [collections.promptTemplates]: demoPromptTemplates,
  [collections.promptRuns]: demoPromptRuns,
  [collections.analysisJobs]: demoAnalysisJobs,
  [collections.analysisResults]: demoAnalysisResults,
  [collections.remixJobs]: demoRemixJobs,
  [collections.remixOutputs]: demoRemixOutputs,
  [collections.trendSnapshots]: demoTrendSnapshots,
  [collections.competitorAccounts]: demoCompetitorAccounts,
  [collections.playbooks]: demoPlaybooks,
  [collections.connectedAccounts]: demoConnectedAccounts,
  [collections.campaigns]: demoCampaigns,
  [collections.publishingQueue]: demoPublishingQueue,
  [collections.watchlistAccounts]: demoWatchlistAccounts,
  [collections.approvalRecords]: demoApprovalRecords,
  [collections.cmsConnections]: demoCmsConnections,
  [collections.blogDrafts]: demoBlogDrafts,
  [collections.assetFolders]: demoAssetFolders,
  [collections.paymentCustomers]: demoPaymentCustomers,
  [collections.paymentAttempts]: demoPaymentAttempts,
  [collections.subscriptions]: demoSubscriptions,
  [collections.activationEvents]: demoActivationEvents,
};
