import type { PlatformCapability } from '@/lib/domain';

export const platformCapabilities: PlatformCapability[] = [
  {
    platform: 'tiktok',
    type: 'social',
    connectedAccountSupport: true,
    creationSupport: true,
    schedulingSupport: true,
    fireAndForgetSupport: true,
    reviewFirstRecommended: false,
    rateLimitSensitivity: 'medium',
    riskLevel: 'medium',
  },
  {
    platform: 'instagram',
    type: 'social',
    connectedAccountSupport: true,
    creationSupport: true,
    schedulingSupport: true,
    fireAndForgetSupport: false,
    reviewFirstRecommended: true,
    rateLimitSensitivity: 'high',
    riskLevel: 'medium',
  },
  {
    platform: 'youtube',
    type: 'social',
    connectedAccountSupport: true,
    creationSupport: true,
    schedulingSupport: true,
    fireAndForgetSupport: true,
    reviewFirstRecommended: false,
    rateLimitSensitivity: 'low',
    riskLevel: 'low',
  },
  {
    platform: 'x',
    type: 'social',
    connectedAccountSupport: true,
    creationSupport: true,
    schedulingSupport: false,
    fireAndForgetSupport: false,
    reviewFirstRecommended: true,
    rateLimitSensitivity: 'high',
    riskLevel: 'high',
  },
  {
    platform: 'linkedin',
    type: 'social',
    connectedAccountSupport: true,
    creationSupport: true,
    schedulingSupport: false,
    fireAndForgetSupport: false,
    reviewFirstRecommended: true,
    rateLimitSensitivity: 'medium',
    riskLevel: 'low',
  },
  {
    platform: 'threads',
    type: 'social',
    connectedAccountSupport: true,
    creationSupport: true,
    schedulingSupport: false,
    fireAndForgetSupport: false,
    reviewFirstRecommended: true,
    rateLimitSensitivity: 'medium',
    riskLevel: 'medium',
  },
  {
    platform: 'wordpress',
    type: 'cms',
    connectedAccountSupport: true,
    creationSupport: true,
    schedulingSupport: true,
    fireAndForgetSupport: true,
    reviewFirstRecommended: false,
    rateLimitSensitivity: 'low',
    riskLevel: 'low',
  },
  {
    platform: 'ghost',
    type: 'cms',
    connectedAccountSupport: true,
    creationSupport: true,
    schedulingSupport: true,
    fireAndForgetSupport: true,
    reviewFirstRecommended: false,
    rateLimitSensitivity: 'low',
    riskLevel: 'low',
  },
  {
    platform: 'webflow',
    type: 'cms',
    connectedAccountSupport: true,
    creationSupport: true,
    schedulingSupport: false,
    fireAndForgetSupport: false,
    reviewFirstRecommended: true,
    rateLimitSensitivity: 'medium',
    riskLevel: 'low',
  },
  {
    platform: 'shopify',
    type: 'cms',
    connectedAccountSupport: true,
    creationSupport: true,
    schedulingSupport: false,
    fireAndForgetSupport: false,
    reviewFirstRecommended: true,
    rateLimitSensitivity: 'low',
    riskLevel: 'low',
  },
];
